# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Site
title: ferdbold
tagline: 'front-end guy from the North'
description: > # this means to ignore newlines until "baseurl:"
  game and front-end developer, LARP&nbsp;aficionado
url: 'http://ferdbold.github.io'
github_username: ferdbold
twitter_username: itsferdbold

author:
  name: 'Frédéric Bolduc'
  url: http://github.com/ferdbold

# Custom vars
github:
  repo: http://github.com/ferdbold/ferdbold.github.io

collections:
  projects:
    output: true